### ISSUE TITLE
Any chance of getting external monitor support?

### ISSUE THREAD

**Issue by uzair-io** [leon0410898/OC-XPS13-9300#5]
Getting external monitor support will basically make this the ultimate laptop for me so is there any workarounds i can use?

**Comment by leon0410898** [comment]
There are two ways to get external display work. 
1.You can change your platform-id to 8a520000. However , this will cause black screen after your laptop  wake from sleep. 2.Another way is connecting to an  egpu. Get egpu to output to an external display.  
I'm still looking for the solution  to this problem.

**Comment by uzair-io** [comment]
also, when after making a boot disk with gibmacos, I copied over your EFI folder, but it comes with a Blocked symbol when trying to boot, I tried adding verbose and it says this platform was not supported, and when I added no_compat_check, it just rebooted 3 seconds after set console end. I have a XPS 13 9300 with I7 1065G7, am I missing something?

**Comment by uzair-io** [comment]
00:000 00:000 OC: Prelinked injection AirportItlwm.kext () - Invalid Parameter
00:298 00:298 OC: Prelinked injection BrightnessKeys.kext () - Invalid Parameter

/\ Grabbed this from opencore log

**Comment by uzair-io** [comment]
Ah sorry my bad, for some reason Mojave and Catalina sounded the same in my head... Made a fresh USB with Catalina and it boots to setup :)

**Comment by uzair-io** [comment]
Also 2 other bugs that I have noticed, the screen brightness is unusually low and occasionally after sleep, the backlight does not light up. I havnt changed the platform ID nor have I got the 4K model so i'm not sure why this happens

**Comment by leon0410898** [comment]
i've mentioned in the known issue.

**Comment by leon0410898** [comment]
However, i've found the solution resently. You can download [applebacklightsmoother](https://github.com/hieplpvip/AppleBacklightSmoother) and place it in the kext folder.

**Comment by uzair-io** [comment]
Thanks, not sure if it was just me but there was a weird right click bug i had too but i fixed that by turning off force touch in trackpad settings. Is a thunderbolt hot plug fix possible using SSDT's or flashing another TB controller firmware?

**Comment by uzair-io** [comment]
Any updates on the Big Sur version,  or any updates on the stability of the Hackintosh in general?

**Comment by psanikos** [comment]
Hello and thanks for your work on this project ! Did you manage to use an external monitor with 8a520000 platform id ; I tried with that and the system just kept rebooting ..

**Comment by leon0410898** [comment]
make sure you are using little endian byte order. If still not work, please upload your config. I'll take a look at it.

**Comment by leon0410898** [comment]
> Any updates on the Big Sur version, or any updates on the stability of the Hackintosh in general?

I'll update Big Sur version today.

**Comment by wzygadlo** [comment]
> Hello and thanks for your work on this project ! Did you manage to use an external monitor with 8a520000 platform id ; I tried with that and the system just kept rebooting ..

Hey I was using the Hackintosh Tool to convert that 8a520000... you can try that `AABSig==` is 8a520000
				
<key>AAPL,ig-platform-id</key>
	<data>AABSig==</data>

**Comment by uzair-io** [comment]
> Hello and thanks for your work on this project ! Did you manage to use an external monitor with 8a520000 platform id ; I tried with that and the system just kept rebooting ..

Use platform id = 0000528a

You split the id into 2s, and wrote it backward.

**Comment by uzair-io** [comment]
I've found an issue with using the device-id solution in Big Sur, it just kernel panics and reboots

`panic(cpu 5 caller 0xffffff8010beaae6): Kernel trap at 0xffffff7faeccfe9a, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000000, CR3: 0x000000047c47c049, CR4: 0x00000000003626e0
RAX: 0xffffff80117f7d40, RBX: 0xffffff936e5d4500, RCX: 0x0000000a884e12bf, RDX: 0x0000000000000308
RSP: 0xffffffb0a9332e80, RBP: 0xffffffb0a9332ea0, RSI: 0xffffffb0a16abdc4, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000308, R10: 0x0000000000000003, R11: 0x0000000000000001
R12: 0xffffff80119ef000, R13: 0xffffff7faeccfe5a, R14: 0xffffff936f50cf08, R15: 0x0000000000000000
RFL: 0x0000000000010282, RIP: 0xffffff7faeccfe9a, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x5, PL: 0, VF: 0

Backtrace (CPU 5), Frame : Return Address
0xffffffb0a93328a0 : 0xffffff8010ab76dd mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffb0a93328f0 : 0xffffff8010bfa0e3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffb0a9332930 : 0xffffff8010bea71a mach_kernel : _kernel_trap + 0x55a
0xffffffb0a9332980 : 0xffffff8010a5ca2f mach_kernel : _return_from_trap + 0xff
0xffffffb0a93329a0 : 0xffffff8010ab6f7d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffb0a9332ac0 : 0xffffff8010ab7268 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffb0a9332b30 : 0xffffff80112b9c9a mach_kernel : _panic + 0x54
0xffffffb0a9332ba0 : 0xffffff8010beaae6 mach_kernel : _sync_iss_to_iks + 0x2c6
0xffffffb0a9332d20 : 0xffffff8010bea7cd mach_kernel : _kernel_trap + 0x60d
0xffffffb0a9332d70 : 0xffffff8010a5ca2f mach_kernel : _return_from_trap + 0xff
0xffffffb0a9332d90 : 0xffffff7faeccfe9a com.apple.driver.AppleHDA : __ZN21AppleHDAHDMI_DPDriver21handleValidEDIDActionEP27HDAGFXHeadAssociationStruct + 0x40
0xffffffb0a9332ea0 : 0xffffff801121192e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffffb0a9332ee0 : 0xffffff7faeccfd50 com.apple.driver.AppleHDA : __ZN21AppleHDAHDMI_DPDriver7messageEjP9IOServicePv + 0x1aa
0xffffffb0a9332f20 : 0xffffff80111e3bb3 mach_kernel : __ZN26_IOServiceInterestNotifier4waitEv + 0xe3
0xffffffb0a9332f40 : 0xffffff80111db5f9 mach_kernel : __ZNK15IORegistryEntry15applyToChildrenEPFvPS_PvES1_PK15IORegistryPlane + 0xa9
0xffffffb0a9332f70 : 0xffffff80111e2f73 mach_kernel : __ZN9IOService17applyToInterestedEPK8OSSymbolPFvP8OSObjectPvES5_ + 0x33
0xffffffb0a9332fa0 : 0xffffff80111e2e02 mach_kernel : __ZN9IOService14messageClientsEjPvm + 0x42
0xffffffb0a9332fe0 : 0xffffff7faec95759 com.apple.driver.AppleHDA : __ZN20AppleHDACodecGeneric7messageEjP9IOServicePv + 0x77
0xffffffb0a9333010 : 0xffffff80111e3bb3 mach_kernel : __ZN26_IOServiceInterestNotifier4waitEv + 0xe3
0xffffffb0a9333030 : 0xffffff80111db5f9 mach_kernel : __ZNK15IORegistryEntry15applyToChildrenEPFvPS_PvES1_PK15IORegistryPlane + 0xa9
0xffffffb0a9333060 : 0xffffff80111e2f73 mach_kernel : __ZN9IOService17applyToInterestedEPK8OSSymbolPFvP8OSObjectPvES5_ + 0x33
0xffffffb0a9333090 : 0xffffff80111e2e02 mach_kernel : __ZN9IOService14messageClientsEjPvm + 0x42
0xffffffb0a93330d0 : 0xffffff80111e3bb3 mach_kernel : __ZN26_IOServiceInterestNotifier4waitEv + 0xe3
0xffffffb0a93330f0 : 0xffffff80111db5f9 mach_kernel : __ZNK15IORegistryEntry15applyToChildrenEPFvPS_PvES1_PK15IORegistryPlane + 0xa9
0xffffffb0a9333120 : 0xffffff80111e2f73 mach_kernel : __ZN9IOService17applyToInterestedEPK8OSSymbolPFvP8OSObjectPvES5_ + 0x33
0xffffffb0a9333150 : 0xffffff80111e2e02 mach_kernel : __ZN9IOService14messageClientsEjPvm + 0x42
0xffffffb0a9333190 : 0xffffff80111e3bb3 mach_kernel : __ZN26_IOServiceInterestNotifier4waitEv + 0xe3
0xffffffb0a93331b0 : 0xffffff80111db5f9 mach_kernel : __ZNK15IORegistryEntry15applyToChildrenEPFvPS_PvES1_PK15IORegistryPlane + 0xa9
0xffffffb0a93331e0 : 0xffffff80111e2f73 mach_kernel : __ZN9IOService17applyToInterestedEPK8OSSymbolPFvP8OSObjectPvES5_ + 0x33
0xffffffb0a9333210 : 0xffffff80111e2e02 mach_kernel : __ZN9IOService14messageClientsEjPvm + 0x42
0xffffffb0a9333250 : 0xffffff80111e3bb3 mach_kernel : __ZN26_IOServiceInterestNotifier4waitEv + 0xe3
0xffffffb0a9333270 : 0xffffff80111db5f9 mach_kernel : __ZNK15IORegistryEntry15applyToChildrenEPFvPS_PvES1_PK15IORegistryPlane + 0xa9
0xffffffb0a93332a0 : 0xffffff80111e2f73 mach_kernel : __ZN9IOService17applyToInterestedEPK8OSSymbolPFvP8OSObjectPvES5_ + 0x33
0xffffffb0a93332d0 : 0xffffff80111e2e02 mach_kernel : __ZN9IOService14messageClientsEjPvm + 0x42
0xffffffb0a9333310 : 0xffffff7faed42e5a com.apple.driver.AppleHDAController : __ZN18AppleHDAController23framebufferEventHandlerEPvP13IOFramebufferiS0_ + 0x13d6
0xffffffb0a9333640 : 0xffffff7faed40fca com.apple.driver.AppleHDAController : __ZN18AppleHDAController20framebufferEventGateEPvP13IOFramebufferiS0_ + 0x1f8
0xffffffb0a9333690 : 0xffffff7fb04d368d com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer24deliverGroupNotificationEijbiPv + 0x425
0xffffffb0a93337d0 : 0xffffff7fb04bdbbd com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer30deliverFramebufferNotificationEiPv + 0x193
0xffffffb0a9333860 : 0xffffff7fb04c8fd5 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer39deliverDisplayModeDidChangeNotificationEv + 0x15
0xffffffb0a9333880 : 0xffffff7fb04c338c com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer7doSetupEb + 0x534
0xffffffb0a9333940 : 0xffffff7fb04d08f1 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer21setupForCurrentConfigEv + 0x2b
0xffffffb0a9333960 : 0xffffff7fb04d1286 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer16doSetDisplayModeEii + 0x1d6
0xffffffb0a93339f0 : 0xffffff7fb04d1038 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer17extSetDisplayModeEP8OSObjectPvP25IOExternalMethodArguments + 0x9a
0xffffffb0a9333a80 : 0xffffff8011240ffe mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffffb0a9333ad0 : 0xffffff7fb04d79e2 com.apple.iokit.IOGraphicsFamily : __ZN23IOFramebufferUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x82
0xffffffb0a9333b20 : 0xffffff801124b13b mach_kernel : _is_io_connect_method + 0x35b
0xffffffb0a9333c80 : 0xffffff8010ba5ad1 mach_kernel : _iokit_server_routine + 0x4d81
0xffffffb0a9333d90 : 0xffffff8010abcde7 mach_kernel : _ipc_kobject_server + 0x337
	Backtrace continues...
      Kernel Extensions in backtrace:
         com.apple.driver.AppleHDA(283.15)[CF9A110A-1923-373D-8D96-42358F038E6A]@0xffffff7faec87000->0xffffff7faed16fff
            dependency: com.apple.driver.AppleHDAController(283.15)[4630157A-5E8A-30C4-B1E0-086659FF18CD]@0xffffff7faed3c000->0xffffff7faed4efff
            dependency: com.apple.driver.DspFuncLib(283.15)[81C59536-3D2B-3F9B-A709-89601F9985CC]@0xffffff7faed69000->0xffffff7faee4bfff
            dependency: com.apple.iokit.IOAudioFamily(300.6.1)[582BC466-CF36-3EE0-B5BE-8A42DC67FEB3]@0xffffff8012f12000->0xffffff8012f2ffff
            dependency: com.apple.iokit.IOGraphicsFamily(585)[C007B094-8597-3C47-BD2F-E1203C60C107]@0xffffff7fb04b3000->0xffffff7fb04e1fff
            dependency: com.apple.iokit.IOHDAFamily(283.15)[E3D540E2-871E-3F39-9998-3DF90E525236]@0xffffff7faee5c000->0xffffff7faee5ffff
            dependency: com.apple.iokit.IONDRVSupport(585)[B6DBE116-5A15-3AC5-9134-90794B61EAB6]@0xffffff7fb04f8000->0xffffff7fb0500fff

Process name corresponding to current thread: WindowServer
Boot args: keepsyms=1 -igfxcdc agdpmod=pikera -rtsx_mimic_linux -noDC9 igfxcflbklt=0 

Mac OS version:
20B5012d

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 24 21:21:05 PDT 2020; root:xnu-7195.50.3.201.1~1/RELEASE_X86_64
Kernel UUID: 2BA1C8BD-9C95-3FA7-B7A4-
KernelCache slide: 0x0000000010800000
KernelCache base:  0xffffff8010a00000
Kernel slide:      0x0000000010810000
Kernel text base:  0xffffff8010a10000
__HIB  text base: 0xffffff8010900000
System model name: MacBookAir9,1 (Mac-)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 45241931665
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000000a88a1243d
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000453bb331e 0x0000000000000000
last started kext at 9970781383: >AGPM	119 (addr 0xffffff7faec66000, size 118784)
loaded kexts:
com.Cycling74.driver.Soundflower	2
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.7
com.zxystd.!I!BFirmware	1.1.2
me.kishorprins.VoodooInput	1.0.8
com.alexandred.VoodooI2CHID	1
com.sinet3k.Sinetek-rtsx	7
com.alexandred.VoodooI2C	2.5.2
com.zxystd.AirportItlwm	1.2.0
as.acidanthera.voodoo.driver.PS2!C	2.1.7
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.1.8
com.sicreative.VoltageShif

`

Also the cursor is sometimes garbled, and I have to close and open lid to fix it.

**Comment by psanikos** [comment]
It didnt  work for me too also the brightness is low ( maxes out at about 60-70%) with the posted efi folder but with the vanilla open core installation the brightness is at 100%

**Comment by uzair-io** [comment]
I think for now I'll be reinstalling windows as there are just too many bugs that make this hackintosh unusable for me. These include:

- Spotty wifi connection
- Battery Life (I did disable CFG-Lock but its still bad about 4 Hours)
- No HDMI out on Big Sur
- No TB3 Hotplug
- Graphics glitches that include:
  - Garbled cursor
  - OEM Dell screen after sleep
- System performance hit (Cinebench windows=2000 Cinebench Mac= 1400)
- Various other ice-lake specific bugs and overall instability

I hope that these get fixed over time, so I'll be keeping an eye for now, (If it gets good enough ill be reinstalling macOS) but since I have another dell AIO (Inspiron 23) computer, I'll be using that as my Hackintosh, and my laptop will have to be windows (Would be linux but programs like fusion 360 do not work on linux)

Thanks for your help, @leon0410898.

**Comment by psanikos** [comment]
If you like to keep the mac os but have windows on the laptop like I do  I installed mac os without an issue on a external nvme drive so I can just connect it every time I want . I had no issues with the installation and performance is pretty much the same .

**Comment by uzair-io** [comment]
Good idea, I may end up going for that instead..., I'll keep a copy installed and updated, and when It's good enough, I'll clone it over to the internal drive.

**Comment by psanikos** [comment]
Yes sadly  it's not yet stable for every day usage...

**Comment by leon0410898** [comment]
> I think for now I'll be reinstalling windows as there are just too many bugs that make this hackintosh unusable for me. These include:
> 
> * Spotty wifi connection
> * Battery Life (I did disable CFG-Lock but its still bad about 4 Hours)
> * No HDMI out on Big Sur
> * No TB3 Hotplug
> * Graphics glitches that include:
>   
>   * Garbled cursor
>   * OEM Dell screen after sleep
> * System performance hit (Cinebench windows=2000 Cinebench Mac= 1400)
> * Various other ice-lake specific bugs and overall instability
> 
> I hope that these get fixed over time, so I'll be keeping an eye for now, (If it gets good enough ill be reinstalling macOS) but since I have another dell AIO (Inspiron 23) computer, I'll be using that as my Hackintosh, and my laptop will have to be windows (Would be linux but programs like fusion 360 do not work on linux)
> 
> Thanks for your help, @leon0410898.

wifi->My wifi works fine. You can update your airportitlwm to the newest alpha version. Maybe the problem will be solved.
battery life-> Yes, battery drain fast. 
HDMI->I've tested before. platform-id 8a520000 works fine for me.
TB3 hotplug->seems no hope.
grphics glitches -> don't press keyboard when your laptop black screen on start. 
dell logo after sleep->make sure that you have followed the bios setting. Disabled all sign of life settings in bios.
system performance-> I'll update 'voltageshift' tutorial recently. After overclock, macos can perform as well as windows. 

Sorry for the late reply. I'm quite busy recently. As you can see, the experience of macos is still not perfect. That's why i"ll create this repo.  I hope more people can join this project and make it better.

**Comment by psanikos** [comment]
I didn’t do the voltage shift and the battery is fine I am getting about 4.5 - 5 hours while coding on Xcode which I have no complains . I too have issues with the WiFi. It fails to connect to a network but after some tries it does and then it works fine (1.1 Kext version ) , sleep works fine . My issues are the sound Which has notable glitches and the external monitor. I still cannot use external monitor neither on Catalina nor on big sur . I use a usb c to HDMI cable to a 4K monitor and as it connects both monitors are full of artifacts...

**Comment by leon0410898** [comment]
sound has notable glitches -> speakers or headphone?
HDMI->seems still no solution for current platform-id now.

**Comment by psanikos** [comment]
On external speakers there are some glitches on the internal the sound sounds more like a mono speaker not a stereo it’s a lot worse than on windows

**Comment by leon0410898** [comment]
![Screen Shot 2020-11-06 at 10 53 13 PM](https://user-images.githubusercontent.com/32150891/98379933-db2e1600-2082-11eb-9fe6-d2f805161ca6.png)
you can scroll the balance bar to see whether your speakers are working or not. For external speaker, I have some problem, too. I can't adjust the volume, but it sounds fine.

**Comment by psanikos** [comment]
They are both working but when playing a video or something like that it sounds like it covers only some part of the sound spectrum ... also when making a video call the microphone sounds noisy

**Comment by psanikos** [comment]
Also only on Skype calls from what I have see there are some random freezes for a couple of seconds during the call . In everything else it’s working great

**Comment by leon0410898** [comment]
Have you removed fakepciid?

**Comment by psanikos** [comment]
No I used the efi folder as it is I only used the Kext for the WiFi and I generated serial number  etc setting it as MacBook Air 9,1 using open core configurator

**Comment by psanikos** [comment]
any update on using 4k external monitor on Big Sur ?

**Comment by wzygadlo** [comment]
@leon0410898 can you please provide some details on how did you do that 
> system performance-> I'll update 'voltageshift' tutorial recently. After overclock, macos can perform as well as windows.

Thank you in advance

**Comment by Yefee** [comment]
External monitor support is greatly appreciated!

**Comment by uzair-io** [comment]
any updates in this project, keen to get macOS running smooth and stable @leon0410898.?

**Comment by uzair-io** [comment]
Issue so is stale and mostly addressed so closing.
